TASK [load the products data] *********************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: [digital envelope routines] unsupported
fatal: [catalogue.lakshmireddy.site]: FAILED! => {"changed": false, "module_stderr": "Shared connection to catalogue.lakshmireddy.site closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/ec2-user/.ansible/tmp/ansible-tmp-1755442079.5538638-5552-237105789035287/AnsiballZ_mongodb_shell.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/ec2-user/.ansible/tmp/ansible-tmp-1755442079.5538638-5552-237105789035287/AnsiballZ_mongodb_shell.py\", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/ec2-user/.ansible/tmp/ansible-tmp-1755442079.5538638-5552-237105789035287/AnsiballZ_mongodb_shell.py\", line 47, in invoke_module\r\n    runpy.run_module(mod_name='ansible_collections.community.mongodb.plugins.modules.mongodb_shell', init_globals=dict(_module_fqn='ansible_collections.community.mongodb.plugins.modules.mongodb_shell', _modlib_path=modlib_path),\r\n  File \"/usr/lib64/python3.9/runpy.py\", line 225, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib64/python3.9/runpy.py\", line 97, in _run_module_code\r\n    _run_code(code, mod_globals, init_globals,\r\n  File \"/usr/lib64/python3.9/runpy.py\", line 87, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_community.mongodb.mongodb_shell_payload_19zve25b/ansible_community.mongodb.mongodb_shell_payload.zip/ansible_collections/community/mongodb/plugins/modules/mongodb_shell.py\", line 327, in <module>\r\n  File \"/tmp/ansible_community.mongodb.mongodb_shell_payload_19zve25b/ansible_community.mongodb.mongodb_shell_payload.zip/ansible_collections/community/mongodb/plugins/modules/mongodb_shell.py\", line 247, in main\r\n  File \"/tmp/ansible_community.mongodb.mongodb_shell_payload_19zve25b/ansible_community.mongodb.mongodb_shell_payload.zip/ansible_collections/community/mongodb/plugins/module_utils/mongodb_shell.py\", line 118, in get_hash_value\r\nValueError: [digital envelope routines] unsupported\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}


solution:
